channels:
- conda-forge
dependencies:
- python=3.12.4
- pip<=25.1.1
- pip:
  - mlflow==2.22.0
  - cloudpickle==3.1.1
  - numpy==2.2.0
  - pandas==2.2.3
  - torch==2.7.0
  - tqdm==4.66.5
name: mlflow-env
